### ISSUE TITLE
Übersetzungsfehler "scrapper"

### ISSUE THREAD

**Issue by M-Reimer** [MarkusEh/plugin.video.vdr.recordings#2]
Hallo,

Wird zwar echt oft falsch gemacht, aber das macht es ja nicht besser.

"scrapper" ist falsch:
https://www.dict.cc/?s=scrapper
Korrekt ist es mit nur einen "p"
https://www.dict.cc/?s=scraper

Ähnlich verhält es sich nit dem Verb:
https://www.dict.cc/?s=scrap
Hier gehört ein "e" ans Ende:
https://www.dict.cc/?s=scrape

**Comment by MarkusEh** [comment]
Danke für den Hinweis.
Ich habe es an allen Stellen, die ich gefunden habe, korrigiert.
